CREATE TABLE ALUNO
(
    ALUNO_ID        SERIAL PRIMARY KEY,
    NOME            VARCHAR(100),
    DATA_NASCIMENTO DATE,
    ALTURA          NUMERIC(3),
    PESO            NUMERIC(3),
    IMC             NUMERIC(3)
);

CREATE TABLE TREINO
(
    TREINO_ID   SERIAL PRIMARY KEY,
    NOME_TREINO VARCHAR(50),
    ALUNO_ID    INTEGER REFERENCES ALUNO (ALUNO_ID)
);

CREATE TABLE TAREFA
(
    TAREFA_ID SERIAL PRIMARY KEY,
    NOME_TAREFA VARCHAR(50),
    TIPO_TAREFA VARCHAR(50),
    TREINO_ID INTEGER REFERENCES TREINO(TREINO_ID)
);

CREATE TABLE EXERCICIO
(
    EXERCICIO_ID SERIAL PRIMARY KEY,
    NOME_EXERCICIO VARCHAR(50),
    IMAGEM_EXERCICIO BYTEA,
    TIPO VARCHAR(50),
    MUSCULO VARCHAR(50),
    EQUIPAMENTO VARCHAR(50),
    DIFICULDADE VARCHAR(50),
    INSTRUCOES VARCHAR(50)
);

CREATE TABLE TAREFAITEM
(
    TAREFAITEM_ID SERIAL PRIMARY KEY,
    QTD_SERIE NUMERIC(3),
    QTD_REPETICOES NUMERIC(3),
    TAREFA_ID INTEGER REFERENCES TAREFA(TAREFA_ID),
    EXERCICIO_ID INTEGER REFERENCES EXERCICIO(EXERCICIO_ID)

);

